// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type Category struct {
	ID       int64
	ParentID sql.NullInt64
	Name     string
}

type CategoryItem struct {
	CategoryID int64
	ItemID     int64
}

type Delivery struct {
	ID      int64
	Status  string
	City    sql.NullString
	Street  sql.NullString
	Zipcode sql.NullString
}

type Item struct {
	ID            int64
	Name          string
	Price         int32
	StockQuantity int32
	Dtype         string
	Author        sql.NullString
	Isbn          sql.NullString
	Artist        sql.NullString
	Etc           sql.NullString
	Director      sql.NullString
	Actor         sql.NullString
	CreatedAt     time.Time
}

type Member struct {
	ID      int64
	Name    string
	City    sql.NullString
	Street  sql.NullString
	Zipcode sql.NullString
}

type Order struct {
	ID         int64
	MemberID   int64
	DeliveryID sql.NullInt64
	OrderDate  time.Time
	Status     string
}

type OrderItem struct {
	ID         int64
	OrderID    int64
	ItemID     int64
	OrderPrice int32
	Count      int32
}
