// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const addItemCategory = `-- name: AddItemCategory :exec
INSERT INTO category_item (category_id, item_id) VALUES (?, ?)
`

type AddItemCategoryParams struct {
	CategoryID int64
	ItemID     int64
}

func (q *Queries) AddItemCategory(ctx context.Context, arg AddItemCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addItemCategory, arg.CategoryID, arg.ItemID)
	return err
}

const createItem = `-- name: CreateItem :execresult
INSERT INTO item (name, price, stock_quantity, dtype, author, isbn, artist, etc, director, actor)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	Name          string
	Price         int32
	StockQuantity int32
	Dtype         string
	Author        sql.NullString
	Isbn          sql.NullString
	Artist        sql.NullString
	Etc           sql.NullString
	Director      sql.NullString
	Actor         sql.NullString
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createItem,
		arg.Name,
		arg.Price,
		arg.StockQuantity,
		arg.Dtype,
		arg.Author,
		arg.Isbn,
		arg.Artist,
		arg.Etc,
		arg.Director,
		arg.Actor,
	)
}

const deleteItemCategories = `-- name: DeleteItemCategories :exec
DELETE FROM category_item WHERE item_id = ?
`

func (q *Queries) DeleteItemCategories(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemCategories, itemID)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, name, price, stock_quantity, dtype, author, isbn, artist, etc, director, actor, created_at
FROM item WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.StockQuantity,
		&i.Dtype,
		&i.Author,
		&i.Isbn,
		&i.Artist,
		&i.Etc,
		&i.Director,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const itemCategoryIDs = `-- name: ItemCategoryIDs :many
SELECT category_id FROM category_item WHERE item_id = ?
`

func (q *Queries) ItemCategoryIDs(ctx context.Context, itemID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, itemCategoryIDs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var category_id int64
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :execresult
UPDATE item SET
    name = ?, price = ?, stock_quantity = ?, dtype = ?,
    author = ?, isbn = ?, artist = ?, etc = ?, director = ?, actor = ?
WHERE id = ?
`

type UpdateItemParams struct {
	Name          string
	Price         int32
	StockQuantity int32
	Dtype         string
	Author        sql.NullString
	Isbn          sql.NullString
	Artist        sql.NullString
	Etc           sql.NullString
	Director      sql.NullString
	Actor         sql.NullString
	ID            int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.Price,
		arg.StockQuantity,
		arg.Dtype,
		arg.Author,
		arg.Isbn,
		arg.Artist,
		arg.Etc,
		arg.Director,
		arg.Actor,
		arg.ID,
	)
}

const updateItemStock = `-- name: UpdateItemStock :exec
UPDATE item SET stock_quantity = ? WHERE id = ?
`

type UpdateItemStockParams struct {
	StockQuantity int32
	ID            int64
}

func (q *Queries) UpdateItemStock(ctx context.Context, arg UpdateItemStockParams) error {
	_, err := q.db.ExecContext(ctx, updateItemStock, arg.StockQuantity, arg.ID)
	return err
}
