// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddItemCategory(ctx context.Context, arg AddItemCategoryParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) (sql.Result, error)
	DeleteItemCategories(ctx context.Context, itemID int64) error
	GetItem(ctx context.Context, id int64) (Item, error)
	ItemCategoryIDs(ctx context.Context, itemID int64) ([]int64, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (sql.Result, error)
	UpdateItemStock(ctx context.Context, arg UpdateItemStockParams) error
}

var _ Querier = (*Queries)(nil)
