// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error)
	GetMember(ctx context.Context, id int64) (Member, error)
}

var _ Querier = (*Queries)(nil)
