// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createMember = `-- name: CreateMember :execresult
INSERT INTO member (name, city, street, zipcode) VALUES (?, ?, ?, ?)
`

type CreateMemberParams struct {
	Name    string
	City    sql.NullString
	Street  sql.NullString
	Zipcode sql.NullString
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMember,
		arg.Name,
		arg.City,
		arg.Street,
		arg.Zipcode,
	)
}

const getMember = `-- name: GetMember :one
SELECT id, name, city, street, zipcode FROM member WHERE id = ?
`

func (q *Queries) GetMember(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Street,
		&i.Zipcode,
	)
	return i, err
}
