// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createDelivery = `-- name: CreateDelivery :execresult
INSERT INTO delivery (status, city, street, zipcode) VALUES (?, ?, ?, ?)
`

type CreateDeliveryParams struct {
	Status  string
	City    sql.NullString
	Street  sql.NullString
	Zipcode sql.NullString
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDelivery,
		arg.Status,
		arg.City,
		arg.Street,
		arg.Zipcode,
	)
}

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (member_id, delivery_id, order_date, status) VALUES (?, ?, ?, ?)
`

type CreateOrderParams struct {
	MemberID   int64
	DeliveryID sql.NullInt64
	OrderDate  time.Time
	Status     string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.MemberID,
		arg.DeliveryID,
		arg.OrderDate,
		arg.Status,
	)
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO order_item (order_id, item_id, order_price, count) VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID    int64
	ItemID     int64
	OrderPrice int32
	Count      int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ItemID,
		arg.OrderPrice,
		arg.Count,
	)
}

const deliveriesByIDs = `-- name: DeliveriesByIDs :many
SELECT id, status, city, street, zipcode FROM delivery WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeliveriesByIDs(ctx context.Context, ids []int64) ([]Delivery, error) {
	query := deliveriesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.City,
			&i.Street,
			&i.Zipcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, member_id, delivery_id, order_date, status FROM orders WHERE id = ?
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.DeliveryID,
		&i.OrderDate,
		&i.Status,
	)
	return i, err
}

const listOrdersByMember = `-- name: ListOrdersByMember :many
SELECT id, member_id, delivery_id, order_date, status
FROM orders WHERE member_id = ? ORDER BY order_date DESC
`

func (q *Queries) ListOrdersByMember(ctx context.Context, memberID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.DeliveryID,
			&i.OrderDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderItemsByOrderIDs = `-- name: OrderItemsByOrderIDs :many
SELECT oi.id, oi.order_id, oi.item_id, i.name AS item_name, oi.order_price, oi.count
FROM order_item oi JOIN item i ON i.id = oi.item_id
WHERE oi.order_id IN (/*SLICE:order_ids*/?)
`

type OrderItemsByOrderIDsRow struct {
	ID         int64
	OrderID    int64
	ItemID     int64
	ItemName   string
	OrderPrice int32
	Count      int32
}

func (q *Queries) OrderItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]OrderItemsByOrderIDsRow, error) {
	query := orderItemsByOrderIDs
	var queryParams []interface{}
	if len(orderIds) > 0 {
		for _, v := range orderIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_ids*/?", strings.Repeat(",?", len(orderIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItemsByOrderIDsRow
	for rows.Next() {
		var i OrderItemsByOrderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ItemID,
			&i.ItemName,
			&i.OrderPrice,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = ? WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
