// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (sql.Result, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error)
	DeliveriesByIDs(ctx context.Context, ids []int64) ([]Delivery, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	ListOrdersByMember(ctx context.Context, memberID int64) ([]Order, error)
	OrderItemsByOrderIDs(ctx context.Context, orderIds []int64) ([]OrderItemsByOrderIDsRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
