// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items": {
            "get": {
                "tags": [
                    "items"
                ],
                "summary": "상품 검색 (동적 쿼리 + 페이징)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "카테고리 ID",
                        "name": "categoryId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "최소 가격",
                        "name": "minPrice",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "최대 가격",
                        "name": "maxPrice",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "newest",
                            "oldest",
                            "price_asc",
                            "price_desc"
                        ],
                        "type": "string",
                        "description": "정렬",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지 크기 (기본 20, 최대 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "오프셋",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "상품 등록",
                "parameters": [
                    {
                        "description": "상품 정보 (type: BOOK|ALBUM|MOVIE)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_catalog_internal_rest.itemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "tags": [
                    "items"
                ],
                "summary": "상품 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "상품 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "put": {
                "tags": [
                    "items"
                ],
                "summary": "상품 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "상품 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "상품 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_catalog_internal_rest.itemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/members": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "summary": "회원 등록",
                "parameters": [
                    {
                        "description": "회원 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_customer_internal_rest.memberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/members/{id}": {
            "get": {
                "tags": [
                    "members"
                ],
                "summary": "회원 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "회원 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/members/{id}/orders": {
            "get": {
                "tags": [
                    "orders"
                ],
                "summary": "주문 내역 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "회원 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "상품 주문",
                "parameters": [
                    {
                        "description": "주문 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ordering_internal_rest.orderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    }
                }
            }
        },
        "/orders/{id}/cancel": {
            "post": {
                "tags": [
                    "orders"
                ],
                "summary": "주문 취소",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "주문 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_shseooo_go-architecture_internal_catalog_internal_domain.ItemType": {
            "type": "string",
            "enum": [
                "BOOK",
                "ALBUM",
                "MOVIE"
            ],
            "x-enum-varnames": [
                "ItemTypeBook",
                "ItemTypeAlbum",
                "ItemTypeMovie"
            ]
        },
        "github_com_shseooo_go-architecture_internal_shared.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zipcode": {
                    "type": "string"
                }
            }
        },
        "internal_catalog_internal_rest.itemRequest": {
            "type": "object",
            "properties": {
                "actor": {
                    "type": "string"
                },
                "artist": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "category_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "director": {
                    "type": "string"
                },
                "etc": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "stock_quantity": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/github_com_shseooo_go-architecture_internal_catalog_internal_domain.ItemType"
                }
            }
        },
        "internal_customer_internal_rest.memberRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/github_com_shseooo_go-architecture_internal_shared.Address"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_ordering_internal_rest.orderRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/github_com_shseooo_go-architecture_internal_shared.Address"
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "count": {
                                "type": "integer"
                            },
                            "item_id": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "member_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shop API",
	Description:      "회원/상품/주문 API — modular monolith, stdlib net/http, sqlc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
